import 'package:flexibletodo/models/task.dart';

const DUMMY_TASK = const [
  Task(
      title: 'Research Work',
      category: 'Academics',
      progressType: 'Gradual',
      todoDueDate: '21/04/05',
      todoStartDate: '21/02/17',
      description: 'I am to search for recent papers online',
      isFinished: false,
      id: 1,
      measurables: [
        'Download Endnote',
        'Install Endnote',
        'visit IEEE and scienceDirect',
        'filter out the papers',
      ]),
  Task(
      title: 'Publishing Paper',
      category: 'Academics',
      progressType: 'Gradual',
      todoDueDate: '21/05/05',
      todoStartDate: '21/02/17',
      description: 'I am to publish my finished papers',
      isFinished: true,
      id: 2,
      measurables: [
        'Visit the publish site'
            'Download Endnote',
        'Filter out the unneccessary stuffs',
        'visit IEEE and scienceDirect',
        'filter out the papers',
      ]),
  Task(
    title: 'Map Work',
    category: 'Work',
    progressType: 'Definite',
    todoDueDate: '21/02/28',
    todoStartDate: '21/02/17',
    description: 'I am to put locations on the maps',
    isFinished: false,
    id: 3,
  ),
  Task(
    title: 'Cook Rice',
    category: 'Family',
    progressType: 'Finite',
    todoDueDate: '21/03/25',
    todoStartDate: '21/02/18',
    description: 'I am to cook different types of soup',
    isFinished: false,
    id: 4,
  ),
  Task(
    title: 'Seive Rice Flour',
    category: 'Food',
    progressType: 'Finite',
    todoDueDate: '21/03/25',
    todoStartDate: '21/02/18',
    description: 'I am to cook different types of soup',
    isFinished: false,
    id: 4,
  ),
];
